* FPClimate
PhD course on "Functional Programming and Climate Impact Research", spring term 2024, study period 4.

*Abstract*: This is a course aimed at PhD students or MSc students
interested in the application of functional programming,
domain-specific languages, and dependent types to climate impact
research.

*Note*. This course is run as a seminar / reading course.
Therefore, you must have the motivation and capacity to digest material with limited teacher presence.

** Lecture / seminar / reading plan
The course is based on material from the following research papers:
+ 2010: [[file:ref/2010_Vulnerability_Modelling.pdf][Vulnerability modelling with functional programming and dependent types]]
+ 2011: [[file:ref/2011_TestingVsProving.pdf][Testing versus proving in climate impact research]]
+ 2012: [[file:ref/2012_DepTy_SciComp_978-3-642-41582-1_9.pdf][Dependently-Typed Programming in Scientific Computing - Examples from Economic Modelling]]
+ 2014: [[file:ref/2014_Jansson-Patrik-Computational-Theory-of-GSS.pdf][Towards a Computational Theory of GSS: a Case for Domain-Specific Languages]]
+ 2017: [[file:ref/2017a_SeqDecProb1.pdf][Sequential decision problems, dependent types and generic solutions]]
+ 2017: [[file:ref/2017b_contributions-to-a-computational-theory-of-policy-advice-and-avoidability.pdf][Contributions to a computational theory of policy advice and avoidability]]
+ 2018: [[file:ref/2018_esd-9-525-2018.pdf][The impact of uncertainty on optimal emission policies]]
+ 2023: [[file:ref/2023_MatterMost_s10666-022-09867-w.pdf][Responsibility Under Uncertainty: Which Climate Decisions Matter Most?]]

Good background reading is provided by the 2023 book [[https://www.cambridge.org/core/books/computing-the-climate/64DAAC995DC84241F8D8605B3779C68A]["Computing the Climate"]] by Steve M. Easterbrook.

** Examination

The course is examined through

+ a sequence of hand-ins (solutions to exercises to be further specified during the course)
+ active participation in most of the weekly seminars

The plan is to award 7.5 higher education credits ([[https://education.ec.europa.eu/education-levels/higher-education/inclusive-and-connected-higher-education/european-credit-transfer-and-accumulation-system][ECTS]]) upon
successful completion of the course.

** Prerequisites
+ BSc degree in Computer Science and Engineering or equivalent.
+ Functional programming (ideally in Haskell, but other languages are also OK)
+ Formal methods (ideally using dependent types, but other methods are also OK)

** Learning outcomes (after completion of the course the student should be able to)
+ Use functional programming specification / implementation / formalisation as a way of understanding new domains
+ Understand a selection of topics in Climate Impact Research
+ Effectively use Haskell and Agda for formalisation

*** Knowledge and understanding
+ Master the terminology, concepts and theories associated with the selected area;
+ Demonstrate deep knowledge and understanding in the area of the course, and insight into current research and development;
+ Demonstrate deep methodological knowledge in the area of the course;

*** Skills and abilities
+ Demonstrate the ability to critically and systematically integrate knowledge and to analyse, assess, and deal with complex issues in the area of the course;

*** Judgement and approach
+ Search for, and extract, necessary information from scientific publications in the selected area of the course, with the purpose of identifying strengths and weakness of solutions, approaches and methodologies.

** Scheduling
+ The course will start in March (2024-03-25) and end in May or June.
+ The preliminary schedule is available below:

| Week | Date           |        Time | Event                               |
|------+----------------+-------------+-------------------------------------|
| [[https://weeknumber.net/?q=13][13]]   | Mon 2024-03-25 | 15.15-17.00 | FPClimate seminar 1                 |
| [[https://weeknumber.net/?q=13][13]]   | Tue 2024-03-26 | 14.00-15.00 | Talk by Anil Madhavapeddy           |
| [[https://weeknumber.net/?q=14][14]]   | (Patrik away)  |             |                                     |
| [[https://weeknumber.net/?q=15][15]]   | Mon 2024-04-08 | 15.15-17.00 | FPClimate seminar 2 (Cezar Ionescu) |
| [[https://weeknumber.net/?q=16][16]]   | Mon 2024-04-15 | 15.15-17.00 | FPClimate seminar 3                 |
| [[https://weeknumber.net/?q=17][17]]   | Mon 2024-04-22 | 15.15-17.00 | FPClimate seminar 4                 |
| [[https://weeknumber.net/?q=18][18]]   | Mon 2024-04-29 | 15.15-17.00 | FPClimate seminar 5                 |
| [[https://weeknumber.net/?q=19][19]]   | Mon 2024-05-06 | 15.15-17.00 | FPClimate seminar 6                 |
| [[https://weeknumber.net/?q=20][20]]   | Mon 2024-05-13 | 15.15-17.00 | FPClimate seminar 7                 |
| [[https://weeknumber.net/?q=21][21]]   | Mon 2024-05-20 | 15.15-17.00 | FPClimate seminar 8                 |
| [[https://weeknumber.net/?q=22][22]]   | Mon 2024-05-27 | 15.15-17.00 | FPClimate seminar 9                 |

+ Time zone: CET (UTC+1) in week 13 (until 2024-03-30), then CEST (UTC+2) from week 14 onwards.
+ For local participants, the room is EDIT 6128 (at Chalmers campus
  Johanneberg) for most seminars.
+ For remote participants, we will provide a zoom link.

* Week 13:
** FPClimate seminar 1
+ Introduction (Patrik Jansson)
** Talk by [[https://4c.cst.cam.ac.uk/staff/professor-anil-madhavapeddy][Prof. Anil Madhavapeddy]]
+ Announced separately
+ Title: (Functional) Programming for the Planet
+ Abstract: As simultaneous crises in emissions and biodiversity sweep the planet, computer systems that analyse the complex interplay of our globe’s health are ever more crucial to guiding policy decisions about how to get out of the mess we’re in. In this talk, we examine how functional programming can contribute to building systems that are more resilient, predictable and reproducible in the face of huge amounts of input data (such as from satellites and ground sensing) that demands precise access control (or else poachers and malicious actors go straight to the source) and requires interactive exploration from non-CS-experts at different levels of the software stack (to do climate science). We will also highlight how our ongoing cross-disciplinary research is having a real impact on conservation projects that are sorely underserved by current systems/PL infrastructure, and also how we went about forging these links. We hope to encourage some of you to form your own local collaborations with your colleagues working on the climate crisis!



* Week 15:
** FPClimate seminar 2
+ Lecture by [[https://www.th-deg.de/en/Cezar-Ionescu-Fakult%C3%A4t%20Angewandte%20Informatik-Professor:innen-1975][Prof. Cezar Ionescu]] about [[file:ref/2010_Vulnerability_Modelling.pdf][Vulnerability modelling]]
* Week 16:
** FPClimate seminar 3
* Week 17:
** FPClimate seminar 4
* Week 18:
** FPClimate seminar 5
* Week 19:
** FPClimate seminar 6
* Week 20:
** FPClimate seminar 7
* Week 21:
** FPClimate seminar 8
* Week 22:
** FPClimate seminar 9

* How to register

+ If you do not need formal credits, you can just contact Patrik Jansson.
+ If you want credits for your local MSc degree, contact the examiner for (DAT235/DIT577): [Ana Bove](https://www.cse.chalmers.se/~bove/)
+ If you want credits for your local PhD degree, obtain the approval of your supervisor and examiner, then contact Patrik Jansson.

* Other resources
+ TODO add links to talks, etc. online
